GET http://127.0.0.1:3000/users
Content-Type: application/json

{}

###

POST http://127.0.0.1:3000/user
Content-Type: application/json

{
    "name": "Dexter",
    "email": "dexter@google.co",
    "password": "dexter8712"
} 

###

GET http://127.0.0.1:3000/user/64ca52f7fc78d2fc0bfab9ea
Content-Type: application/json

{}

###

PUT http://127.0.0.1:3000/user/64ca52f7fc78d2fc0bfab9ea
Content-Type: application/json

{
    "name": "Dexter Junior",
    "email": "dexter@google.co",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNhNTJmN2ZjNzhkMmZjMGJmYWI5ZWEiLCJpYXQiOjE2OTA5ODExMTJ9.qvtWE2u4RfQ4sc9ix6LVugSBTF8l_UqaKjHOCu24hJI"
}

###

POST http://127.0.0.1:3000/validateuser
Content-Type: application/json

{
    "email": "dexter@google.co",
    "password": "dexter8712"
}
 
###
